CREATE TABLE CHAPTER
(
    ID           VARCHAR(36)  NOT NULL,
    TITLE        VARCHAR(128) NOT NULL,
    DESCRIPTION  VARCHAR(128) NULL,
    CONTENT      TEXT         NULL,
    DURATION     TIME         NULL,
    COURSE_ID    VARCHAR(36)  NOT NULL,
    CREATED_BY   VARCHAR(32)  NOT NULL,
    CREATED_DATE TIMESTAMP    NOT NULL,
    UPDATED_BY   VARCHAR(32)  NOT NULL,
    UPDATED_DATE TIMESTAMP    NOT NULL,
    PRIMARY KEY (ID, TITLE),
    CONSTRAINT CHAPTER_COURSE_ID_FK
        FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID)
);