CREATE TABLE BOARD
(
    ID           VARCHAR(36) NOT NULL,
    BOARD_TYPE   VARCHAR(32) NOT NULL,
    DESCRIPTION  TEXT        NULL,
    CREATED_BY   VARCHAR(32) NOT NULL,
    CREATED_DATE TIMESTAMP   NOT NULL,
    UPDATED_BY   VARCHAR(32) NULL,
    UPDATED_DATE TIMESTAMP   NOT NULL,
    PRIMARY KEY (ID, BOARD_TYPE)
);