CREATE TABLE PAYMENT
(
    ID             VARCHAR(36)   NOT NULL,
    STUDENT_ID     VARCHAR(20)   NOT NULL,
    COURSE_ID      VARCHAR(36)   NOT NULL,
    AMOUNT         DECIMAL(4, 2) NOT NULL,
    PAYMENT_DATE   DATE          NOT NULL,
    PAYMENT_METHOD VARCHAR(36)   NOT NULL,
    TRANSACTION_ID VARCHAR(36)   NOT NULL,
    PAYMENT_STATUS VARCHAR(16)   NOT NULL,
    CREATED_BY     VARCHAR(32)   NOT NULL,
    CREATED_DATE   TIMESTAMP     NOT NULL,
    UPDATED_BY     VARCHAR(32)   NOT NULL,
    UPDATED_DATE   TIMESTAMP     NOT NULL,
    PRIMARY KEY (ID, COURSE_ID, STUDENT_ID),
    CONSTRAINT PAYMENT_PAYMENT_METHOD_UINDEX
        UNIQUE (PAYMENT_METHOD),
    CONSTRAINT PAYMENT_COURSE_ID_FK
        FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID),
    CONSTRAINT PAYMENT_STUDENT_STUDENT_ID_FK
        FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (STUDENT_ID)
);