CREATE TABLE STUDENT
(
    ID              VARCHAR(36)   NOT NULL,
    STUDENT_ID      VARCHAR(20)   NOT NULL PRIMARY KEY,
    STUDENT_CLASS   VARCHAR(32)   NOT NULL,
    PREV_PERCENTAGE DECIMAL(4, 2) NOT NULL,
    LEARNING_GOAL   TEXT          NOT NULL,
    PARENT_EMAIL    VARCHAR(64)   NOT NULL,
    PARENT_PHONE    VARCHAR(15)   NOT NULL,
    CREATED_BY      VARCHAR(32)   NOT NULL,
    CREATED_DATE    TIMESTAMP     NOT NULL,
    UPDATED_BY      VARCHAR(32)   NOT NULL,
    UPDATED_DATE    TIMESTAMP     NOT NULL,
    CONSTRAINT STUDENT_STUDENT_ID_INDEX
        UNIQUE (STUDENT_ID),
    CONSTRAINT STUDENT_PK
        UNIQUE (ID)
);