CREATE TABLE FORUM_TOPIC
(
    ID           VARCHAR(36)  NOT NULL
        PRIMARY KEY,
    COURSE_ID    VARCHAR(36)  NOT NULL,
    TITLE        VARCHAR(64)  NOT NULL,
    DESCRIPTION  VARCHAR(128) NULL,
    CREATOR      VARCHAR(20)  NOT NULL,
    CREATED_BY   VARCHAR(32)  NOT NULL,
    CREATED_DATE TIMESTAMP    NOT NULL,
    UPDATED_BY   VARCHAR(32)  NOT NULL,
    UPDATED_DATE TIMESTAMP    NULL,
    CONSTRAINT FORUM_TOPIC_TITLE_UINDEX
        UNIQUE (TITLE),
    CONSTRAINT FORUM_TOPIC_COURSE_ID_FK
        FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID)
);