CREATE TABLE TUTOR
(
    ID                VARCHAR(36) NULL,
    TUTOR_ID          VARCHAR(20) NOT NULL PRIMARY KEY,
    NAME              VARCHAR(64) NULL,
    EDUCATION         TEXT        NULL,
    EXPERIENCE        TEXT        NULL,
    COMPLETED_DEGREES TEXT        NULL,
    CREATED_BY        VARCHAR(32) NOT NULL,
    CREATED_DATE      TIMESTAMP   NOT NULL,
    UPDATED_BY        VARCHAR(32) NOT NULL,
    UPDATED_DATE      TIMESTAMP   NOT NULL,
    CONSTRAINT TUTOR_TUTOR_ID_UINDEX
        UNIQUE (TUTOR_ID),
    CONSTRAINT TUTOR_PK2
        UNIQUE (ID)
);