CREATE TABLE COURSE
(
    ID           VARCHAR(36)   NOT NULL,
    TITLE        VARCHAR(128)  NOT NULL,
    TUTOR_ID     VARCHAR(64)   NOT NULL,
    BOARD_ID     VARCHAR(36)   NOT NULL,
    LEVEL        VARCHAR(32)   NOT NULL,
    DURATION     TIME          NULL,
    LECTURES     VARCHAR(128)  NULL,
    DESCRIPTION  TEXT          NULL,
    PRICE        DECIMAL(4, 2) NOT NULL,
    CREATED_BY   VARCHAR(32)   NOT NULL,
    CREATED_DATE TIMESTAMP     NOT NULL,
    UPDATED_BY   VARCHAR(32)   NOT NULL,
    UPDATED_DATE TIMESTAMP     NOT NULL,
    PRIMARY KEY (ID, TITLE),
    CONSTRAINT COURSE_BOARD_ID_FK
        FOREIGN KEY (BOARD_ID) REFERENCES BOARD (ID),
    CONSTRAINT COURSE_TUTOR_TUTOR_ID_FK
        FOREIGN KEY (TUTOR_ID) REFERENCES TUTOR (TUTOR_ID)
);