CREATE TABLE AVAILABILITY
(
    ID           VARCHAR(36) NOT NULL,
    TUTOR_ID     VARCHAR(20) NOT NULL,
    START_TIME   DATETIME    NOT NULL,
    END_TIME     DATETIME    NOT NULL,
    DURATION     TIME        NULL,
    NOTES        TEXT        NULL,
    CREATED_BY   VARCHAR(32) NOT NULL,
    CREATED_DATE TIMESTAMP   NOT NULL,
    UPDATED_BY   VARCHAR(32) NOT NULL,
    UPDATED_DATE TIMESTAMP   NOT NULL,
    PRIMARY KEY (ID, TUTOR_ID),
    CONSTRAINT AVAILABILITY_TUTOR_ID_UINDEX
        UNIQUE (TUTOR_ID),
    CONSTRAINT AVAILABILITY_TUTOR_TUTOR_ID_FK
        FOREIGN KEY (TUTOR_ID) REFERENCES TUTOR (TUTOR_ID)
);