CREATE TABLE PRICE_HISTORY
(
    ID           VARCHAR(36)   NOT NULL PRIMARY KEY,
    COURSE_ID    VARCHAR(36)   NOT NULL,
    PRICE        DECIMAL(4, 2) NOT NULL,
    CREATED_BY   VARCHAR(32)   NOT NULL,
    CREATED_DATE TIMESTAMP     NOT NULL,
    UPDATED_BY   VARCHAR(32)   NOT NULL,
    UPDATED_DATE TIMESTAMP     NULL,
    CONSTRAINT PRICE_HISTORY_COURSE_ID_FK
        FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID)
);