CREATE TABLE ANNOUNCEMENT
(
    ID            VARCHAR(36)  NULL,
    TITLE         VARCHAR(128) NOT NULL PRIMARY KEY,
    CONTENT       TEXT         NULL,
    CREATOR       VARCHAR(32)  NULL,
    CREATION_DATE TIMESTAMP    NULL,
    COURSE_ID     VARCHAR(32)  NULL,
    CREATED_BY    VARCHAR(32)  NULL,
    CREATED_DATE  TIMESTAMP    NULL,
    UPDATED_BY    VARCHAR(32)  NULL,
    UPDATED_DATE  TIMESTAMP    NULL,
    CONSTRAINT ANNOUNCEMENT_ID_PK
        UNIQUE (ID),
    CONSTRAINT ANNOUNCEMENT_TITLE_INDEX
        UNIQUE (TITLE)
);