CREATE TABLE IF NOT EXISTS USER
(
    ID            VARCHAR(20)  NOT NULL,
    USERNAME      VARCHAR(32)  NOT NULL PRIMARY KEY,
    EMAIL         VARCHAR(128) NOT NULL,
    PHONE         VARCHAR(15)  NOT NULL,
    ADDRESS       VARCHAR(256) NOT NULL,
    GENDER        VARCHAR(20)  NOT NULL,
    DATE_OF_BIRTH DATE         NOT NULL,
    ROLE          VARCHAR(20)  NOT NULL,
    CREATED_BY    VARCHAR(32)  NOT NULL,
    CREATED_DATE  TIMESTAMP    NOT NULL,
    UPDATED_BY    VARCHAR(32)  NOT NULL,
    UPDATED_DATE  TIMESTAMP    NOT NULL,
    CONSTRAINT USER_ROLE_UINDEX UNIQUE (ROLE)
);