CREATE TABLE REVIEW
(
    ID           VARCHAR(36) NOT NULL,
    REVIEWER_ID  VARCHAR(20) NOT NULL,
    REVIEW_ID    VARCHAR(36) NOT NULL,
    RATING       INT         NOT NULL,
    DATE         DATE        NOT NULL,
    COMMENTS     TEXT        NULL,
    CREATED_BY   VARCHAR(32) NOT NULL,
    CREATED_DATE TIMESTAMP   NOT NULL,
    UPDATED_BY   VARCHAR(32) NOT NULL,
    UPDATED_DATE TIMESTAMP   NOT NULL,
    PRIMARY KEY (ID, REVIEW_ID),
    CONSTRAINT REVIEW_REVIEWER_ID_UINDEX
        UNIQUE (REVIEWER_ID)
);